{{- if .Values.blackbox.podDisruptionBudget -}}
{{ if $.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    {{- include "kube-prometheus-stack.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kube-prometheus-stack.selectorLabels" . | nindent 6 }}
{{ toYaml .Values.blackbox.podDisruptionBudget | indent 2 }}
{{- end }}
