{{- if .Values.blackbox.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}
  {{- with .Values.blackbox.prometheusRule.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "kube-prometheus-stack.labels" . | nindent 4 }}
    {{- with .Values.blackbox.prometheusRule.additionalLabels -}}
{{- toYaml . | nindent 4 -}}
    {{- end }}
spec:
  {{- with .Values.blackbox.prometheusRule.rules }}
  groups:
    - name: {{ template "kube-prometheus-stack.name" $ }}
      rules: {{ toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
