{{- if .Values.blackbox.serviceMonitor.enabled }}
{{- range .Values.blackbox.serviceMonitor.targets }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "kube-prometheus-stack.fullname" $ }}-{{ .name }}
  namespace: {{ template "kube-prometheus-stack.namespace" $ }}
  labels:
    {{- include "kube-prometheus-stack.labels" $ | nindent 4 }}
    {{- if or $.Values.blackbox.serviceMonitor.defaults.labels .labels }}
    {{- toYaml (.labels | default $.Values.blackbox.serviceMonitor.defaults.labels) | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - port: http
    scheme: {{ $.Values.blackbox.serviceMonitor.scheme }}
    {{- if $.Values.blackbox.serviceMonitor.bearerTokenFile }}
    bearerTokenFile: {{ $.Values.blackbox.serviceMonitor.bearerTokenFile }}
    {{- end }}
    {{- if $.Values.blackbox.serviceMonitor.tlsConfig }}
    tlsConfig: {{ toYaml $.Values.blackbox.serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
    path: "/probe"
    interval: {{ .interval | default $.Values.blackbox.serviceMonitor.defaults.interval }}
    scrapeTimeout: {{ .scrapeTimeout | default $.Values.blackbox.serviceMonitor.defaults.scrapeTimeout }}
    params:
      module:
      - {{ .module | default $.Values.blackbox.serviceMonitor.defaults.module }}
      target:
      - {{ .url }}
    metricRelabelings:
      - sourceLabels: [instance]
        targetLabel: instance
        replacement: {{ .url }}
      - sourceLabels: [target]
        targetLabel: target
        replacement: {{ .name }}
        {{- range $targetLabel, $replacement := .additionalMetricsRelabels | default $.Values.blackbox.serviceMonitor.defaults.additionalMetricsRelabels }}
      - targetLabel: {{ $targetLabel | quote }}
        replacement: {{ $replacement | quote }}
        {{- end }}
{{- if concat (.additionalRelabeling | default list) $.Values.blackbox.serviceMonitor.defaults.additionalRelabeling }}
    relabelings:
{{ toYaml (concat (.additionalRelabeling | default list) $.Values.blackbox.serviceMonitor.defaults.additionalRelabeling) | indent 6 }}
{{- end }}
  jobLabel: "{{ $.Release.Name }}"
  selector:
    matchLabels:
      {{- include "kube-prometheus-stack.selectorLabels" $ | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ template "kube-prometheus-stack.namespace" $ }}
{{- end }}
{{- end }}
