{{- if .Values.blackbox.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-prometheus-stack.blackbox.serviceAccountName" . }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    {{ include "kube-prometheus-stack.labels" . | indent 4 }}
{{- if .Values.blackbox.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
